name: CMake

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  BUILD_TYPE: Release

jobs:
  build_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake ./TGEngine -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Cache
        uses: actions/cache@v3.0.6
        with:
           path: ${{github.workspace}}/build/deps
           key: wincache
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: TGAppWindows
          path: ${{github.workspace}}/build/TGApp.exe
          if-no-files-found: error
          
  build_linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Update Clang
        run: sudo apt install clang-14 --install-suggests
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake ./TGEngine -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_COMPILER=clang
      - name: Cache
        uses: actions/cache@v3.0.6
        with:
           path: ${{github.workspace}}/build/deps
           key: linuxcache
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: TGAppLinux
          path: ${{github.workspace}}/build/TGApp.exe
          if-no-files-found: error
